import { Title } from "@ui5/webcomponents-react";

const columns = [
  {
    Header: <Title>ID</Title>,
    accessor: "id",
  },
  {
    Header: <Title>Material Code</Title>,
    accessor: "material_code",
  },
  {
    Header: <Title>Material Description</Title>,
    accessor: "material_description",
  },
  {
    Header: <Title>Supplier</Title>,
    accessor: "supplier",
  },
  {
    Header: <Title>Created At</Title>,
    accessor: "created_at",
  },
  {
    Header: <Title>Created By</Title>,
    accessor: "created_by",
  },
  {
    Header: <Title>Cost Center</Title>,
    accessor: "cost_center",
  },
];
const data = [
  {
    id: 1,
    material_code: "00680673",
    material_description: "Laptop Lenovo Thinkpad T4",
    supplier: "Lenovo",
    created_at: "14/01/2025",
    created_by: "John Doe",
    cost_center: "101090",
  },
  {
    id: 2,
    material_code: "12345678",
    material_description: "Impressora HP LaserJet Pro",
    supplier: "HP",
    created_at: "10/01/2025",
    created_by: "Jane Smith",
    cost_center: "101095",
  },
  {
    id: 3,
    material_code: "98765432",
    material_description: "Monitor Dell UltraSharp",
    supplier: "Dell",
    created_at: "20/01/2025",
    created_by: "Michael Johnson",
    cost_center: "101100",
  },
  {
    id: 4,
    material_code: "56789012",
    material_description: "Mouse Logitech G Pro Wireless",
    supplier: "Logitech",
    created_at: "15/01/2025",
    created_by: "Emily Chen",
    cost_center: "101092",
  },
  {
    id: 5,
    material_code: "34567890",
    material_description: "Teclado Mecânico Corsair K70 RGB",
    supplier: "Corsair",
    created_at: "12/01/2025",
    created_by: "David Lee",
    cost_center: "101098",
  },
  {
    id: 6,
    material_code: "78901234",
    material_description: "Fones de Ouvido Sony WH-1000XM4",
    supplier: "Sony",
    created_at: "18/01/2025",
    created_by: "Olivia Martinez",
    cost_center: "101102",
  },
  {
    id: 7,
    material_code: "23456789",
    material_description: "Projetor Epson Home Cinema",
    supplier: "Epson",
    created_at: "17/01/2025",
    created_by: "Daniel Kim",
    cost_center: "101094",
  },
  {
    id: 8,
    material_code: "45678901",
    material_description: "Câmera Web Logitech C920s Pro",
    supplier: "Logitech",
    created_at: "19/01/2025",
    created_by: "Sophia Hernandez",
    cost_center: "101096",
  },
  {
    id: 9,
    material_code: "67890123",
    material_description: "Tablet Samsung Galaxy Tab S8",
    supplier: "Samsung",
    created_at: "16/01/2025",
    created_by: "Benjamin Taylor",
    cost_center: "101101",
  },
  {
    id: 10,
    material_code: "89012345",
    material_description: "Smartphone Apple iPhone 14 Pro",
    supplier: "Apple",
    created_at: "13/01/2025",
    created_by: "Ava Wilson",
    cost_center: "101093",
  },
  {
    id: 11,
    material_code: "01234567",
    material_description: "Cartuchos de Tinta HP Original",
    supplier: "HP",
    created_at: "14/01/2025",
    created_by: "Ethan Hall",
    cost_center: "101097",
  },
  {
    id: 12,
    material_code: "23456789",
    material_description: "Papel A4 90g",
    supplier: "Copimax",
    created_at: "15/01/2025",
    created_by: "Mia Moore",
    cost_center: "101103",
  },
  {
    id: 13,
    material_code: "45678901",
    material_description: "Canetas Bic Cristal",
    supplier: "Bic",
    created_at: "16/01/2025",
    created_by: "Noah Campbell",
    cost_center: "101099",
  },
  {
    id: 14,
    material_code: "67890123",
    material_description: "Pendrive SanDisk Extreme Pro",
    supplier: "SanDisk",
    created_at: "17/01/2025",
    created_by: "Olivia Rodriguez",
    cost_center: "101091",
  },
  {
    id: 15,
    material_code: "89012345",
    material_description: "Hub USB 7 Portas",
    supplier: "Belkin",
    created_at: "18/01/2025",
    created_by: "Liam Evans",
    cost_center: "101104",
  },
];

const mocks = {
  columns,
  data,
};

export default mocks;
